target-version = "py311"
line-length = 100

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # import sorting
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
]

[format]
quote-style = "preserve"
docstring-code-format = true


